### ISSUE TITLE
merge: Malignant Choroid Plexus Neoplasm  + Choroid Plexus Carcinoma

### ISSUE THREAD

**Issue by cmungall** [NCI-Thesaurus/thesaurus-obo-edition#16]
Malignant Choroid Plexus Neoplasm has only 1 child:

 * [NCIT:C3709](http://purl.obolibrary.org/obo/NCIT_C3709) ! Epithelial Neoplasm
    * [NCIT:C3473](http://purl.obolibrary.org/obo/NCIT_C3473) ! Choroid Plexus Neoplasm
      * [NCIT:C4533](http://purl.obolibrary.org/obo/NCIT_C4533) ! Malignant Choroid Plexus Neoplasm  
          * [NCIT:C4715](http://purl.obolibrary.org/obo/NCIT_C4715) ! Choroid Plexus Carcinoma

it also lacks a text definition

What other children of MCPN are there? Given that malignant neoplasms from epithelia are carcinomas, should these be merged?

**Comment by NCIEVS** [comment]
From the NCIt editing group:

"Malignant choroid plexus neoplasm is not exactly a synonym with choroid plexus carcinoma. The vast majority of malignant neoplasms of the choroid plexus are carcinomas arising from the choroid plexus epithelium. However, there are cases of PRIMARY choroid plexus non-Hodgkin lymphomas (NHLs) reported in the literature which are either of B- or T-cell phenotype. These NHLs tend to have an aggressive clinical course. There are also cases of PRIMARY choroid plexus meningioma arising from the stroma (non-epithelial) part of the choroid plexus reported. We have the latter term in NCIt, but it is not under the malignant choroid plexus neoplasm, because it can be histologically benign, atypical, or malignant. We have it under intracranial meningioma, but it does have the role disease_has_primary_anatomic_site: choroid plexus.

"The reason that we have not added the term choroid plexus lymphoma in the NCIt is because this tumor is very rare and we will add it in NCIt only if it is requested. Alternatively, such rare tumors can be post-coordinated with the anatomic site involved (preferably). As for the missing definition for malignant choroid plexus neoplasm, I just added it in NCIt. Here it is:

"A malignant neoplasm that arises from the choroid plexus. The vast majority are carcinomas."

**Comment by cmungall** [comment]
Thanks for your response,

The definition of [Choroid Plexus Neoplasm](http://purl.obolibrary.org/obo/NCIT_C3473) states that it *originates from the choroid plexus epithelium*. If my understanding is correct, CPnH-lymphomas do not arise from the CP epithelium, which means it could not be a child of 'NCIT:C4533 ! Malignant Choroid Plexus Neoplasm', which inherits from C3473.

Perhaps the definition of CP neoplasm should be relaxed to be about site rather the cell type of origin? Or made consistent with the new `malignant CP neoplasm` definition, i.e. not referencing epithelium specifically

**Comment by NCIEVS** [comment]
Thanks for the catch, the definition has now been changed in the master baseline, should be available in the next release.  Here's the new def:
"An intraventricular neoplasm that originates from the choroid plexus.  The vast majority of choroid plexus neoplasms originate from the epithelial layer and include the choroid plexus papilloma, atypical choroid plexus papilloma, and choroid plexus carcinoma."

**Comment by cmungall** [comment]
Thanks!
